Parallelize diffeomorphic registration
dipy/dipy pull request #1613
Opened 2018-08-10 04:22 UTC by RicciWoo

Parallelize diffeomorphic registration using prange and local function:
1. parallelized \_compose_vector_fields_3d in vector_fields.pyx;
2. parallelized warp_3d in vector_fields.pyx.

To specify number of threads: add num_threads to SymmetricDiffeomorphicRegistration
> sdr = SymmetricDiffeomorphicRegistration(metric, level_iters, num_threads=4)

2019-01-17 01:22 UTC, Borda requested changes
valuable change but some code enhancement would be welcome

2019-01-17 01:22 UTC, Borda commented on dipy/align/imwarp.py
> +        if self.dim == 2:
what about rather set the setting the nb of threads
```
num_threads = self.num_threads if self.dim <= 2 else 1
warped = warp_f(image, self.forward, affine_idx_in, affine_idx_out, affine_disp, out_shape, num_threads)
```

2019-01-17 01:22 UTC, Borda commented on dipy/align/imwarp.py
> +        if self.dim == 2:
similar as above...

2019-01-17 01:22 UTC, Borda commented on dipy/align/imwarp.py
> +        num_threads : int
I would rater follow the `sklearn` syntax, using `-1` for default/all threads used instead introducing `None`

2019-01-17 01:22 UTC, Borda commented on dipy/align/imwarp.py
> +        if self.dim == 2:
setting just the right number of threads would avoid doubling the code length
```
num_threads = self.num_threads if self.dim <= 2 else 1
...
```

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +            dkk = d1[k, i, j, 0]
the name convention `dkk` or `diii` is very unintuitive

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +    if num_threads != 0:
rather use `if num_threads > 0:`

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +    num_threads : int
rather use `-1` as default number, see `sklearn`

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +                dkk = d1[k, i, j, 0]
introducing one more for cycle instead repetitive using triple commands would make the code much more readable

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +            # This is the only place we access d1[k, i, j]
introducing one more for cycle instead repetitive using triple commands would make the code much more readable

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +                dk = _apply_affine_3d_x0(
is line break really needed?

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +    num_threads : int
rather use `-1` for default, see `sklearn`

2019-01-17 01:22 UTC, Borda commented on dipy/align/vector_fields.pyx
> +            if affine_idx_in is None:
similar as above, simplify the code using one more inter loop

2019-04-27 15:46 UTC, Borda commented on dipy/align/imwarp.py
> +                 prealign=None, num_threads=None):
put it on a new line

2019-04-27 15:46 UTC, Borda commented on dipy/align/imwarp.py
> +                                              None, self.num_threads)
use a new line

2026-08-19 13:04 UTC, TomasGuija commented
Hello @skoudoro. I have been inspecting this PR, along with Codex, and I believe it may be closed now. All the contributions where already covered through #4073 and #4083.

2026-08-19 15:55 UTC, skoudoro commented
I had a deeper check and you are right @TomasGuija.

Thank you for this old work @RicciWoo.

Closing. (superseded by #4073 + #4083)

2026-08-19 15:55 UTC, closed without merging