Fixed Handling Negative Values for Denoising
dipy/dipy pull request #2318
Opened 2021-02-05 17:41 UTC by ShreyasFadnavis

Small fix as an alternative to clipping to a minimum via `np.clip` !

2021-02-05 20:57 UTC, skoudoro requested changes
Hi @ShreyasFadnavis,

Thank you for this fix. I think you need to review your change or update your test. This change make your test less robust. See below the error:

```python
    @needs_sklearn
    def test_patch2self_random_noise():
        S0 = 30 + 2 * np.random.standard_normal((20, 20, 20, 50))
    
        bvals = np.repeat(30, 50)
        S0nb = p2s.patch2self(S0, bvals, model='ols')
    
>       assert_greater(S0nb.min(), S0.min())
E           AssertionError: 21.1010317819 > 21.1010317819
```

2021-02-05 21:14 UTC, ShreyasFadnavis commented
> Hi @ShreyasFadnavis,
> 
> Thank you for this fix. I think you need to review your change or update your test. This change make your test less robust. See below the error:
> 
> ```python
>     @needs_sklearn
>     def test_patch2self_random_noise():
>         S0 = 30 + 2 * np.random.standard_normal((20, 20, 20, 50))
>     
>         bvals = np.repeat(30, 50)
>         S0nb = p2s.patch2self(S0, bvals, model='ols')
>     
> >       assert_greater(S0nb.min(), S0.min())
> 
> E           AssertionError: 21.1010317819 > 21.1010317819
> ```

Thanks @skoudoro ... On it!

2021-02-11 21:53 UTC, skoudoro reviewed
It seems ready to go. It will be good to have another opinion before merging

2021-02-11 21:55 UTC, arokem commented
Generally looks good. Just want to make sure that I understand what this is for: you are trying to preserve the variance, while avoiding negative values?

2021-02-11 22:16 UTC, ShreyasFadnavis commented
> Generally looks good. Just want to make sure that I understand what this is for: you are trying to preserve the variance, while avoiding negative values?

Yes exactly! This was pointed out to me by @RafaelNH one of his datasets, where this issue was messing up the `b0`'s. I will add this as an option than forcing it always.

2021-02-15 18:07 UTC, pep8speaks commented
Hello @ShreyasFadnavis, Thank you for updating !

* In the file [`dipy/denoise/patch2self.py`](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/patch2self.py):

> [Line 320:24](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/patch2self.py#L320): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 326:29](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/patch2self.py#L326): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 329:29](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/patch2self.py#L329): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'

* In the file [`dipy/denoise/tests/test_patch2self.py`](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/tests/test_patch2self.py):

> [Line 4:26](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/tests/test_patch2self.py#L4): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 26:34](https://github.com/dipy/dipy/blob/388841584c7d217b125c527a63ee4efd52aff60f/dipy/denoise/tests/test_patch2self.py#L26): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2021-02-15 18:16 UTC, ShreyasFadnavis commented
Okay! I am done 👍🏽 Let me know if something seems off!

2021-02-17 21:28 UTC, skoudoro reviewed
Hi @ShreyasFadnavis,

See below for some comments. is it possible to add a test for each case to make sure the expected behavior appears. Thank you

2021-02-17 21:28 UTC, skoudoro commented on dipy/denoise/patch2self.py
> +    if shift_intensity == True and clip_negative_vals == False:
in python, for a boolean value, you should avoid `==True` and `is True`. Can you update that everywhere?

In this specific case, `if shift_intensity and not clip_negative_vals:`

For your information, a quick test:
```python
In [1]: 1 is True                                                                                                                                                                                            
Out[1]: False

In [2]: 1 == True                                                                                                                                                                                            
Out[2]: True
```

2021-02-17 21:28 UTC, skoudoro commented on dipy/denoise/patch2self.py
>          if verbose is True:
`if verbose` instead

2021-02-17 21:28 UTC, skoudoro commented on dipy/denoise/patch2self.py
> +    elif clip_negative_vals == True and shift_intensity == False:
same comment as above

2021-02-17 21:28 UTC, skoudoro commented on dipy/denoise/patch2self.py
> +    elif clip_negative_vals == True and shift_intensity == True:
same comment as above

2021-02-17 21:53 UTC, ShreyasFadnavis commented on dipy/denoise/tests/test_patch2self.py
> +    S0den_shift = p2s.patch2self(S0, bvals, model='ols', shift_intensity=True)
@skoudoro the test should be handled here 👍🏽

2021-02-18 18:13 UTC, skoudoro approved these changes
Thank you for the update @ShreyasFadnavis.

Looks good to me, waiting for the CI's and any other feedback?

2021-02-19 18:24 UTC, Garyfallidis commented
+1 from me just restarted some bots. If these are okay then please merge.

2021-02-19 20:49 UTC, merged