Add `patch_radius` parameter to Patch2Self denoise workflow
dipy/dipy pull request #2792
Opened 2023-04-26 17:04 UTC by pcamach2

Addresses #2791

2023-04-26 19:09 UTC, skoudoro requested changes
Nice! Thank you for this @pcamach2! 

it is missing the part to check if it is a `list of int` or just a `int`. You can look at this example: https://github.com/dipy/dipy/blob/976217e547c4da6bfb210642adbb071c2ee40dd9/dipy/workflows/denoise.py#L310.

Also, it would be great if you could update the test : https://github.com/dipy/dipy/blob/976217e547c4da6bfb210642adbb071c2ee40dd9/dipy/workflows/tests/test_denoise.py#L43

Thank you!

2023-04-26 19:09 UTC, skoudoro commented on dipy/workflows/denoise.py
> +        patch_radius : int or 1 D array, optional
`variable int, optional` instead 

you can look at this example: https://github.com/dipy/dipy/blob/976217e547c4da6bfb210642adbb071c2ee40dd9/dipy/workflows/denoise.py#L277

2023-04-26 21:20 UTC, pcamach2 commented
Thank you for your review, @skoudoro!

Please let me know if anything else needs adjusting for this PR

2023-04-26 21:33 UTC, skoudoro approved these changes
Looks good to me! 

Waiting for the CI's to finish, then I will go ahead and merge it.

2023-04-27 01:52 UTC, skoudoro commented
ok, all green, merging. Thanks again @pcamach2 !

2023-04-27 01:52 UTC, merged