Shilpi's Week 5 blog
dipy/dipy pull request #2836
Opened 2023-06-27 18:38 UTC by shilpiprd

2023-08-08 18:20 UTC, skoudoro requested changes
Hi @shilpiprd,

file is empty ?

2023-08-08 18:42 UTC, shilpiprd commented
Sorry, I think this was a confusion. I'll upload here right away.

2023-08-08 18:51 UTC, skoudoro commented
Hi @shilpiprd,

- Blog 6th, has been merged so no need to add it to this PR.
- Blog 5th is still empty

2023-08-09 17:58 UTC, shilpiprd commented
Hey Serge, it seems on the official blog page, I haven't uploaded Week1 blog and I've renamed Week2 blog as Week1. So should I make a submission now for Week1 blog and the increase 1 on all weeks from there after ? 
Thanks,

2023-08-09 18:58 UTC, skoudoro commented
just call it week0 it is fine

2023-08-10 06:38 UTC, shilpiprd commented
> 

Well, the thing is that I'm starting from Week0 in my official blog as well. Also, I think Rafael said a few days ago that I haven't submitted 1 blog meaning I'm in the 1 missing blog zone. So this is basically the reason why on my blog I'm posting Week10, but in dipy blog page it's Week11. So, should I make changes in PSF or leave it as it is ?

2023-08-11 14:14 UTC, skoudoro commented
You can leave it as it is. 

You will just have to pay attention when you create you final report. You final report should look like this: https://fury.gl/latest/posts/2023/2023-01-24-final-report-praneeth.html

on the last section, you can see link to PSF blog and fury blog. You will have to do the same on PSF blog + DIPY blog

2023-08-12 18:22 UTC, shilpiprd commented
Serge actually I just noticed  that in the end I would have to list out all the blogs, both in PSF and DIPY side by side. Problem is that Week5 in PSF and Week5 in DIPY won't match. What do you suggest ? Also, according to DIPY's blog I'm one blog ahead.

2023-08-14 19:51 UTC, skoudoro commented
let's meet to clarify all of that. it should be a quick meeting. we can do that on wednesday.

2023-08-18 05:54 UTC, skoudoro requested changes
Hi @shilpiprd,

See below the comments. thanks for the future update

2023-08-18 05:54 UTC, skoudoro commented on doc/posts/2023/2023_07_06_shilpi_week5.rst
> +
the header is missing 
```
.. post:: July 06 2023
    :author: Shilpi Prasad
    :tags: google
    :category: gsoc
```

2023-08-18 05:54 UTC, skoudoro commented on doc/posts/2023/2023_07_06_shilpi_week5.rst
> +This week I worked on improving the design_matrix that I'd previously created. It wasn't according to the PEP8 standards, I managed to modify it according to the appropriate format.
design matrix: 2 words

2023-08-18 05:54 UTC, skoudoro commented on doc/posts/2023/2023_07_06_shilpi_week5.rst
> +My procedure for this part was going through the 2 different modules and comparing the functions, and making note on functions which would have to be implemented in CTI as CTI has a very different de
strange sentence, to improve
design matrix: 2 words

2023-08-18 05:54 UTC, skoudoro commented on doc/posts/2023/2023_07_06_shilpi_week5.rst
> +This week I intend to further implement the Fit class and also generate tests for the already implemented functions under the Fit class.
`method` instead of `functions`

2023-08-18 05:54 UTC, skoudoro commented on doc/posts/2023/2023_07_06_shilpi_week5.rst
> +And also write tests to make sure that the signals generated in the QTI model are the same as the ones done in CTI_pred.
cti_pred : add backtick

2023-08-21 15:22 UTC, skoudoro approved these changes
Thank you @shilpiprd for the update

it is much better. Merging

2023-08-21 15:23 UTC, merged