Pushing Week 8 blog
dipy/dipy pull request #2847
Opened 2023-07-27 05:01 UTC by shilpiprd

2023-08-18 06:07 UTC, skoudoro requested changes
Before a deeper review, can you 

- check again all the markup:
  * filename, code, function name, etc with backtick
  * remove all the underscore of design matrix
- make shorter sentences to improve readability

Thanks

2023-08-18 06:07 UTC, skoudoro commented on doc/posts/2023/2023_07_27_Shilpi_week8.rst
> +Generating Fit Functions : Week 9
PR say week 8+9
filename say week8
title say week 9

Can you update that and make it more consistent.....

2023-08-20 11:25 UTC, shilpiprd commented
So, I improved whatever I thought could be improved. But please let me know if there's anything else I could improve.

2023-08-21 15:27 UTC, skoudoro approved these changes
Thanks for the reshaping. Looks good, merging

2023-08-21 15:27 UTC, merged