MAINT: fix warning
dipy/dipy pull request #3194
Opened 2024-04-17 21:12 UTC by alexrockhill

Fixes issue here https://github.com/dipy/dipy/pull/3153#issuecomment-2053689778.

I considered setting `legacy=False` in `peaks_from_model` but I only saw that in tests so I figured best just to capture and ignore the warning.

2024-04-17 21:12 UTC, pep8speaks commented
Hello @alexrockhill, Thank you for submitting the Pull Request !

* In the file [`dipy/workflows/tests/test_reconst_dti.py`](https://github.com/dipy/dipy/blob/daacb52b1f5a3b353d157f2882412684fbac627b/dipy/workflows/tests/test_reconst_dti.py):

> [Line 26:25](https://github.com/dipy/dipy/blob/daacb52b1f5a3b353d157f2882412684fbac627b/dipy/workflows/tests/test_reconst_dti.py#L26): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

Do see the [DIPY coding Style guideline](https://github.com/dipy/dipy/blob/master/doc/devel/coding_style_guideline.rst)

2024-04-17 21:13 UTC, alexrockhill commented
cc @jhlegarreta

2024-04-19 00:31 UTC, alexrockhill commented
Ah my bad, only saw and fixed the first one, will fix the other ones tomorrow.

2024-04-19 19:33 UTC, alexrockhill commented
Ok, oddly there's more warnings but I checked and none of them traced back to any of my recent changes https://github.com/dipy/dipy/actions/runs/8758110095/job/24038195569?pr=3194

2024-04-19 19:46 UTC, jhlegarreta commented
> Ok, oddly there's more warnings but I checked and none of them traced back to any of my recent changes

They come from PR #3151.

2024-04-19 20:02 UTC, skoudoro commented
> They come from PR https://github.com/dipy/dipy/pull/3151.

My bad, I should have check those warnings before merging.... 

Looking forward to put the flag to treat warning as error....

2024-04-19 21:52 UTC, alexrockhill commented
Ok to merge?

2024-04-19 23:56 UTC, jhlegarreta requested changes
The way warnings are caught is the following:
https://github.com/dipy/dipy/blob/53c18e1997f70fc3ee1d742fd30429b208314e0c/dipy/workflows/tests/test_tracking.py#L75

An exact match to the message is sought.

2024-04-22 19:04 UTC, jhlegarreta commented on doc/examples/reconst_dki.py
> +from dipy.denoise.localpca import mppca
Done in https://github.com/dipy/dipy/pull/3197/files#diff-3883fbe25a03fa8e050608f8e3808888811b4e02f06c195b36a76083b331d4b7R94

We should document better how to set up/use the pre-commit hooks. Sorry for that.

In the meantime, the cleanest approach is to (assuming you have a python (virtual) environment set up to work on dipy):
1. Squash all your commits into a single commit (all these changes utitmately do a single thing, i.e. capturing the warnings properly) and follow the DIPY commit subject prefixes: https://github.com/dipy/dipy/blob/50ec2b60209e9945e9dedfd61beaa446f1054a2c/doc/devel/commit_codes.rst
1. Rebase on `master` (assumes `origin` is your remote fork, `upstream` is the dipy org repository):
    ```
    git checkout master
    git fetch upstream
    git merge upstream/master
    git push origin master
    git checkout {your_branch_name}
    git rebase origin/master
    ```
    You may need to solve the conflicts when rebasing on `master`.

    This way we do not introduce unnecessary merge commits.

1. Once that is done, in order to ensure that your local changes comply with the import sorting rules:
    ```
    pip install pre-commit
    pip install ruff
    ruff --fix
    ```
1. Add the changes if files are modified using and do a `git commit --amend --no-edit` if the feature/maint/bugfix/etc. change has been commited with an appropriate message (avoids introducing a new commit to tell about the style change, which is not informative of the feature/maint/bugfix/etc.) ; else, `git commit`.

Hope this helps.

2024-04-22 19:23 UTC, alexrockhill commented
Hopefully that should fix the out-of-sync-with-`master`-issues, thanks for the instructions

2024-04-22 22:00 UTC, jhlegarreta commented on doc/examples/reconst_dki.py
> +from dipy.denoise.localpca import mppca
Addressed in 3c2b823.

2024-04-22 22:37 UTC, jhlegarreta approved these changes
CI failures are unrelated.

I wish the commit message honored only the changes made, but approving to move forward.

2024-04-23 13:11 UTC, merged