BF: Cast operation explicitly to `double` in PCA noise estimation
dipy/dipy pull request #3205
Opened 2024-04-27 17:15 UTC by jhlegarreta

Cast operation explicitly to `double` in PCA noise estimation method.

Fixes:
```
dipy/denoise/pca_noise_estimate.cp39-win_amd64.pyd.p/pca_noise_estimate.c(20299):
 warning C4244: '=': conversion from 'npy_intp' to 'double', possible loss of data
```

raised for example at:
https://github.com/dipy/dipy/actions/runs/8822497881/job/24220827033#step:8:319

2024-04-27 18:38 UTC, jhlegarreta commented
The warning is gone:
https://github.com/dipy/dipy/actions/runs/8861496546/job/24333420258?pr=3205#step:8:284
https://github.com/dipy/dipy/actions/runs/8861496546/job/24333419836?pr=3205#step:8:317

2024-04-28 02:07 UTC, skoudoro requested changes
Hi @jhlegarreta,

Thank you for doing this. See below my comment.

2024-04-28 15:06 UTC, jhlegarreta commented on dipy/denoise/denspeed.pyx
> +    patch_vol_size = <double> ((P + P + 1) * (P + P + 1) * (P + P + 1))
:+1: Done in 33eb489. Applies to both cases.

2024-04-29 16:06 UTC, skoudoro approved these changes
Thanks @jhlegarreta, merging

2024-04-29 16:06 UTC, merged