NF: Applying Decorators in Module (segment)
dipy/dipy pull request #3258
Opened 2024-06-17 00:24 UTC by deka27

## This PR is to apply keyword decorator to functions in segment module.

This PR is dependent on the main PR, which should be merged first.

## Main PR:
- #3239

2024-06-17 00:24 UTC, pep8speaks commented
Hello @deka27, Thank you for submitting the Pull Request !

* In the file [`dipy/segment/bundles.py`](https://github.com/dipy/dipy/blob/00bcfe9fa2e227a7c12c1e4d724ef555a3717e23/dipy/segment/bundles.py):

> [Line 163:89](https://github.com/dipy/dipy/blob/00bcfe9fa2e227a7c12c1e4d724ef555a3717e23/dipy/segment/bundles.py#L163): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 88 characters)





* In the file [`dipy/segment/mask.py`](https://github.com/dipy/dipy/blob/00bcfe9fa2e227a7c12c1e4d724ef555a3717e23/dipy/segment/mask.py):

> [Line 132:89](https://github.com/dipy/dipy/blob/00bcfe9fa2e227a7c12c1e4d724ef555a3717e23/dipy/segment/mask.py#L132): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 88 characters)

















Do see the [DIPY coding Style guideline](https://github.com/dipy/dipy/blob/master/doc/devel/coding_style_guideline.rst)

2024-07-03 16:39 UTC, deka27 commented on dipy/segment/clusteringspeed.pyx
> +from dipy.testing.decorators import warning_for_keywords
Done.

2024-07-03 16:40 UTC, deka27 commented on dipy/segment/featurespeed.pyx
> +from dipy.testing.decorators import warning_for_keywords
Done.

2024-07-03 17:54 UTC, deka27 commented
This should be good to go

2024-07-04 07:35 UTC, skoudoro reviewed
Hi @deka27, 

See below the comments. thanks for the future fixing.

2024-07-04 07:35 UTC, skoudoro commented on dipy/segment/clustering.py
>      def __init__(self, refdata=None):
Why `*` is missing here? any reason ?

2024-07-04 07:35 UTC, skoudoro commented on dipy/segment/metricspeed.pyx
> +from dipy.testing.decorators import warning_for_keywords
imported but not use so useless. To remove I suppose

2024-07-04 07:37 UTC, skoudoro requested changes
Also, reviewing take time, so please, check multiple time before requesting review. it will help both of us

2024-07-06 07:28 UTC, skoudoro approved these changes
All good, thanks @deka27, merging

2024-07-06 07:28 UTC, merged