NF: Applying Decorators in Module (Workflow)
dipy/dipy pull request #3263
Opened 2024-06-17 12:00 UTC by deka27

## This PR is to apply keyword decorator to functions in workflow module.

This PR is dependent on the main PR, which should be merged first.

## Main PR:
- #3239

2024-06-17 12:01 UTC, pep8speaks commented
Hello @deka27, Thank you for submitting the Pull Request !















* In the file [`dipy/workflows/base.py`](https://github.com/dipy/dipy/blob/2aa86e2c3ecd754dff0fe4bd5d3573dec2560b4c/dipy/workflows/base.py):

> [Line 322:1](https://github.com/dipy/dipy/blob/2aa86e2c3ecd754dff0fe4bd5d3573dec2560b4c/dipy/workflows/base.py#L322): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 323:5](https://github.com/dipy/dipy/blob/2aa86e2c3ecd754dff0fe4bd5d3573dec2560b4c/dipy/workflows/base.py#L323): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)











* In the file [`dipy/workflows/multi_io.py`](https://github.com/dipy/dipy/blob/2aa86e2c3ecd754dff0fe4bd5d3573dec2560b4c/dipy/workflows/multi_io.py):

> [Line 127:89](https://github.com/dipy/dipy/blob/2aa86e2c3ecd754dff0fe4bd5d3573dec2560b4c/dipy/workflows/multi_io.py#L127): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 88 characters)
> [Line 222:1](https://github.com/dipy/dipy/blob/2aa86e2c3ecd754dff0fe4bd5d3573dec2560b4c/dipy/workflows/multi_io.py#L222): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace















Do see the [DIPY coding Style guideline](https://github.com/dipy/dipy/blob/master/doc/devel/coding_style_guideline.rst)

2024-07-02 17:41 UTC, skoudoro commented
Can you rebase and fix the format since https://github.com/dipy/dipy/pull/3239 is merged ? Thanks!

2024-07-04 07:41 UTC, skoudoro requested changes
Hi @deka27, 

Can you check why it is failing? see the comment below also

2024-07-04 07:41 UTC, skoudoro commented on dipy/workflows/mask.py
>      def run(self, input_files, lb, ub=np.inf, out_dir="", out_mask="mask.nii.gz"):
missing `*`. any reason ?

2024-07-06 11:41 UTC, itellaetxe reviewed
I checked all the changes. All the function definitions that you changed seem to be correctly updated in the argument definition section. OK

On the other hand, we should check why the CIs are failing

Good work

2024-07-08 20:06 UTC, skoudoro approved these changes
thank you for this @deka27, merging

2024-07-08 20:07 UTC, merged