DOC: Use references bibliography file for DIPY citation file
dipy/dipy pull request #3319
Opened 2024-08-16 13:10 UTC by jhlegarreta

Use references bibliography file for DIPY citation file.

Add missing citations to `references.bib`.

2024-08-16 14:15 UTC, jhlegarreta commented
Increases the number of warnings so making it a draft for now.

2024-08-18 16:50 UTC, jhlegarreta commented
These should also be transitioned:
https://docs.dipy.org/stable/reconstruction_models_list.html

2024-08-27 16:51 UTC, skoudoro reviewed
Hi @jhlegarreta,

Overall, it looks good. 

I just have a doubt about the `README.rst`. because it will look strange on DIPY Github homepage.  For sure it will not be processed and we do not use the `README` in the doc generation.

I think you should revert these changes on the `README`. 

Thank you for the future update

2024-08-27 22:05 UTC, jhlegarreta commented
:+1: Removed with the last force push.

2024-08-27 22:50 UTC, jhlegarreta commented
The doc build is generating warnings in the code base:
https://github.com/dipy/dipy/actions/runs/10586647103/job/29335853394?pr=3319#step:5:1750

Compare to:
https://github.com/dipy/dipy/actions/runs/10569986141/job/29283731136#step:5:1669

e.g.
https://github.com/dipy/dipy/actions/runs/10586647103/job/29335853394?pr=3319#step:5:893

That reference does exist in this commit:
https://github.com/dipy/dipy/blob/3baae5048438959c96f315594e0d391f9504a021/doc/references.bib#L2057

And the refs in the rst file are not being found:
https://github.com/dipy/dipy/actions/runs/10586647103/job/29335853394?pr=3319#step:5:1084

So not sure what happens here. Cannot devote time to this now, so @skoudoro let me know when you have time to have a look. Thanks.

2024-08-28 20:06 UTC, skoudoro requested changes
Hi @jhlegarreta,

Thank you for this.

for some reason, it works as expected when we remove `:list: enumerated` from https://github.com/dipy/dipy/blob/ec07b657b22f7baca0eecd9777fa9a918fea12fb/doc/user_guide/bibliography.rst?plain=1#L8

So I proposed that you remove it for now.

ref: https://github.com/jupyter-book/jupyter-book/issues/1662

See also my comment below. 

Last point, it does not look so great (even if the references works well). We need a better way to render this.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/abbb9757-4034-44f9-97aa-e3b6566caeab">

2024-08-28 22:41 UTC, jhlegarreta commented on doc/references.bib
> +@article{Garyfallidis2014,
:ok_hand:. Fixed in 0a14e04. Force pushed. Also, maybe the absence of a comma after the cite key explained the missing citations. I am waiting for the CI to remove the `:list: enumerated` option.

2024-08-28 22:44 UTC, jhlegarreta commented
> Last point, it does not look so great (even if the references works well). We need a better way to render this.

Using biblatex there is a way to put the entire citation at a given place instead of using a cross-reference using `fullcite`. That would be ideal here, but did not find a way in `sphinxbibtex-contrib`.

Honestly, I would prioritize here consistency and reduce maintenance burden, which I would say we achieve with these changes. People can click on the links and C&P the refs or copy the bibtex, the later not being possible without these changes.

2024-08-28 23:08 UTC, jhlegarreta commented on doc/references.bib
> +@article{Garyfallidis2014,
> I am waiting for the CI result to remove the :list: enumerated option.

Errors persisted with the option, so removed in the last force push.

2024-08-29 04:50 UTC, skoudoro approved these changes
ok, all good, Thanks @jhlegarreta, merging

2024-08-29 04:50 UTC, merged