MAINT: Address changes to API with new (1.6) version of cvxpy.
dipy/dipy pull request #3417
Opened 2024-11-28 05:54 UTC by arokem

2024-11-30 04:30 UTC, skoudoro commented
Hi @arokem,

Thank you for this. Can you say more before merging this? What is sparsity and what happens if we have an old version of CVXPY ? Should we update our requirement to be safe ?

2024-12-02 23:41 UTC, arokem commented
Yes, I think that we should require the newest version of CVXPY to be on the safe side. 

I am not sure what this parameter was, to be honest, but looks like the tests pass without it so 🤷

2024-12-05 21:15 UTC, skoudoro requested changes
Back to DIPY 😅, 

So I checked, and sparsity just changed shape.
instead of `sparsity=[(0, 0), (0,1), (0,2), ...]` it is `sparsity=[(0,0,0, ...), (0, 1, 2, ...)]`

it would be great to keep it because it impact performance on some model. We just to check `cvxpy` version and plug in the right shape.  See below.

Thank you for the future update

2024-12-05 21:15 UTC, skoudoro commented on dipy/core/optimize.py
> -        sparsity = [(i, j) for i in range(m) for j in range(i, m)]
```python
if Version(cvxpy.__version__) < Version('1.6'):
    sparsity = [(i, j) for i in range(m) for j in range(i, m)]
else:
    sparsity =  [range(m), range(m)]
```

2024-12-05 21:15 UTC, skoudoro commented on dipy/core/optimize.py
> -        self._X = cvxpy.Parameter((m, m), sparsity=sparsity)  # Design matrix
to keep like before

2024-12-05 21:26 UTC, arokem commented
Thanks for looking into this. Changes made in 72897943a

2024-12-05 21:30 UTC, skoudoro commented on dipy/core/optimize.py
> +from distutils.version import Version
```suggestion
from packaging.version import Version
```

2024-12-06 04:20 UTC, arokem commented
Seems like these recent changes are now making the tests fail. Are you sure my original proposal was incorrect? The tests all passed with that change.

2024-12-06 05:03 UTC, skoudoro commented
> Seems like these recent changes are now making the tests fail. Are you sure my original proposal was incorrect? The tests all passed with that change.

It was not incorrect, just making thing slower.  Let me go a bit deeper into that issue and if no easy solution we revert back to what you did. Sorry about that.

2024-12-06 05:16 UTC, arokem commented
Oh gotcha. Yeah, worth a bit more digging...

2024-12-08 03:15 UTC, skoudoro commented
ok, I think it is due to [`load_sdp_constraints`](https://github.com/dipy/dipy/blob/927246108f6aa67283003a46b63f2deeced9becb/dipy/data/__init__.py#L410) but I am not 100% sure.

I did a bit more digging but I did not find an easy solution. I do not want to spend more time on this.

Furthermore, this feature was available but not active/used in reality following this issue https://github.com/cvxpy/cvxpy/issues/2038.

So, we can safely remove it since it was already ignored.

Sorry for all of this @arokem. you can get back to what you did initially, remove sparsity, then we can merge.

thanks!

2024-12-08 03:16 UTC, skoudoro commented
ps: just remove the 2 last commits

2024-12-08 03:29 UTC, arokem commented
OK - done! Also rebased on master for good measure.

2024-12-08 05:38 UTC, merged